name: terraform-apply

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-main
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::488179516291:role/acme-ci-deploy
          aws-region: us-east-2

      - name: init
        run: terraform init -input=false

      - name: apply
        run: terraform apply -input=false -no-color -auto-approve
