name: terraform-plan

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write # OIDC — no long-lived AWS keys anywhere in this org
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::488179516291:role/acme-ci-deploy
          aws-region: us-east-2

      - name: fmt check (whole repo)
        run: terraform fmt -check -recursive ..

      - name: init
        run: terraform init -input=false

      - name: validate
        run: terraform validate -no-color

      - name: plan
        run: terraform plan -input=false -no-color
